// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0nT1ZLx13iMhqCCAdyUoQnNKoX_QPf4',
    appId: '1:151734339769:web:e4d396298cbc260a7db368',
    messagingSenderId: '151734339769',
    projectId: 'crud-e2e0e',
    authDomain: 'crud-e2e0e.firebaseapp.com',
    storageBucket: 'crud-e2e0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrYyPmWIFWVn03IDZ6PkjocAO1D6ptP8',
    appId: '1:151734339769:android:8f79ee8949fe937e7db368',
    messagingSenderId: '151734339769',
    projectId: 'crud-e2e0e',
    storageBucket: 'crud-e2e0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAapkE4B3EYFhvB_PYloyI--Fk8gjONAFw',
    appId: '1:151734339769:ios:273889a1ad1a255e7db368',
    messagingSenderId: '151734339769',
    projectId: 'crud-e2e0e',
    storageBucket: 'crud-e2e0e.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAapkE4B3EYFhvB_PYloyI--Fk8gjONAFw',
    appId: '1:151734339769:ios:273889a1ad1a255e7db368',
    messagingSenderId: '151734339769',
    projectId: 'crud-e2e0e',
    storageBucket: 'crud-e2e0e.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz0nT1ZLx13iMhqCCAdyUoQnNKoX_QPf4',
    appId: '1:151734339769:web:85584c4cdaa804c87db368',
    messagingSenderId: '151734339769',
    projectId: 'crud-e2e0e',
    authDomain: 'crud-e2e0e.firebaseapp.com',
    storageBucket: 'crud-e2e0e.firebasestorage.app',
  );
}
